project:
  type: website
  output-dir: _site

website:
  title: MISO manual
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Manual

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    lang: en
