
# This file is automatically generated, you probably don't want to edit this

anosimOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anosimOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            factor = NULL,
            strata = NULL,
            transform = "none",
            distance = "bray",
            distBinary = FALSE,
            seed = 0,
            anosimN = 999, ...) {

            super$initialize(
                package="tofu",
                name="anosim",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..factor <- jmvcore::OptionVariable$new(
                "factor",
                factor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..strata <- jmvcore::OptionVariable$new(
                "strata",
                strata,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..transform <- jmvcore::OptionList$new(
                "transform",
                transform,
                options=list(
                    "none",
                    "sqrt",
                    "fourthroot",
                    "log",
                    "pa",
                    "wisconsin",
                    "hellinger",
                    "total",
                    "max",
                    "frequency",
                    "normalize",
                    "range",
                    "standardize",
                    "chi.square",
                    "rclr"),
                default="none")
            private$..distance <- jmvcore::OptionList$new(
                "distance",
                distance,
                options=list(
                    "bray",
                    "jaccard",
                    "euclidean",
                    "manhattan",
                    "canberra",
                    "kulczynski",
                    "gower",
                    "morisita",
                    "horn",
                    "mountford",
                    "raup",
                    "binomial",
                    "chao",
                    "cao",
                    "clark",
                    "altGower",
                    "mahalanobis"),
                default="bray")
            private$..distBinary <- jmvcore::OptionBool$new(
                "distBinary",
                distBinary,
                default=FALSE)
            private$..seed <- jmvcore::OptionNumber$new(
                "seed",
                seed,
                default=0,
                min=0)
            private$..anosimN <- jmvcore::OptionNumber$new(
                "anosimN",
                anosimN,
                default=999,
                min=1)

            self$.addOption(private$..vars)
            self$.addOption(private$..factor)
            self$.addOption(private$..strata)
            self$.addOption(private$..transform)
            self$.addOption(private$..distance)
            self$.addOption(private$..distBinary)
            self$.addOption(private$..seed)
            self$.addOption(private$..anosimN)
        }),
    active = list(
        vars = function() private$..vars$value,
        factor = function() private$..factor$value,
        strata = function() private$..strata$value,
        transform = function() private$..transform$value,
        distance = function() private$..distance$value,
        distBinary = function() private$..distBinary$value,
        seed = function() private$..seed$value,
        anosimN = function() private$..anosimN$value),
    private = list(
        ..vars = NA,
        ..factor = NA,
        ..strata = NA,
        ..transform = NA,
        ..distance = NA,
        ..distBinary = NA,
        ..seed = NA,
        ..anosimN = NA)
)

anosimResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anosimResults",
    inherit = jmvcore::Group,
    active = list(
        warnings = function() private$.items[["warnings"]],
        summary = function() private$.items[["summary"]],
        global = function() private$.items[["global"]],
        pairwise = function() private$.items[["pairwise"]],
        note = function() private$.items[["note"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="ANOSIM")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="warnings",
                title="Notes and Warnings"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Data Summary",
                rows=0,
                columns=list(
                    list(
                        `name`="item",
                        `title`="Item",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="global",
                title="Global Test",
                rows=0,
                columns=list(
                    list(
                        `name`="statistic",
                        `title`="Statistic",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="number"),
                    list(
                        `name`="p",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue"),
                    list(
                        `name`="permutations",
                        `title`="Permutations",
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="pairwise",
                title="Pairwise ANOSIM",
                rows=0,
                columns=list(
                    list(
                        `name`="contrast",
                        `title`="Contrast",
                        `type`="text"),
                    list(
                        `name`="r",
                        `title`="R",
                        `type`="number"),
                    list(
                        `name`="p",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="note",
                title="Notes"))}))

anosimBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anosimBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tofu",
                name = "anosim",
                version = c(0,1,0),
                options = options,
                results = anosimResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' ANOSIM
#'
#'
#' @param data .
#' @param vars .
#' @param factor .
#' @param strata .
#' @param transform .
#' @param distance .
#' @param distBinary .
#' @param seed .
#' @param anosimN .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$warnings} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$global} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pairwise} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$note} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
anosim <- function(
    data,
    vars,
    factor,
    strata = NULL,
    transform = "none",
    distance = "bray",
    distBinary = FALSE,
    seed = 0,
    anosimN = 999) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("anosim requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(factor)) factor <- jmvcore::resolveQuo(jmvcore::enquo(factor))
    if ( ! missing(strata)) strata <- jmvcore::resolveQuo(jmvcore::enquo(strata))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(factor), factor, NULL),
            `if`( ! missing(strata), strata, NULL))

    for (v in factor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in strata) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- anosimOptions$new(
        vars = vars,
        factor = factor,
        strata = strata,
        transform = transform,
        distance = distance,
        distBinary = distBinary,
        seed = seed,
        anosimN = anosimN)

    analysis <- anosimClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
