
# This file is automatically generated, you probably don't want to edit this

clusterOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clusterOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            labels = NULL,
            transform = "none",
            distance = "bray",
            showLabels = TRUE, ...) {

            super$initialize(
                package="tofu",
                name="cluster",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "nominal",
                    "ordinal",
                    "id"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                default=NULL)
            private$..transform <- jmvcore::OptionList$new(
                "transform",
                transform,
                options=list(
                    "none",
                    "sqrt",
                    "fourthroot",
                    "log",
                    "pa",
                    "wisconsin",
                    "hellinger",
                    "total",
                    "max",
                    "frequency",
                    "normalize",
                    "range",
                    "standardize",
                    "chi.square",
                    "rclr"),
                default="none")
            private$..distance <- jmvcore::OptionList$new(
                "distance",
                distance,
                options=list(
                    "bray",
                    "jaccard",
                    "euclidean",
                    "manhattan",
                    "canberra",
                    "kulczynski",
                    "gower",
                    "morisita",
                    "horn",
                    "mountford",
                    "raup",
                    "binomial",
                    "chao",
                    "cao",
                    "clark",
                    "altGower",
                    "mahalanobis"),
                default="bray")
            private$..showLabels <- jmvcore::OptionBool$new(
                "showLabels",
                showLabels,
                default=TRUE)

            self$.addOption(private$..vars)
            self$.addOption(private$..labels)
            self$.addOption(private$..transform)
            self$.addOption(private$..distance)
            self$.addOption(private$..showLabels)
        }),
    active = list(
        vars = function() private$..vars$value,
        labels = function() private$..labels$value,
        transform = function() private$..transform$value,
        distance = function() private$..distance$value,
        showLabels = function() private$..showLabels$value),
    private = list(
        ..vars = NA,
        ..labels = NA,
        ..transform = NA,
        ..distance = NA,
        ..showLabels = NA)
)

clusterResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clusterResults",
    inherit = jmvcore::Group,
    active = list(
        guidance = function() private$.items[["guidance"]],
        summary = function() private$.items[["summary"]],
        warnings = function() private$.items[["warnings"]],
        dendrogram = function() private$.items[["dendrogram"]],
        interpretation = function() private$.items[["interpretation"]],
        settings = function() private$.items[["settings"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Cluster analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="guidance",
                title="Getting started",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "showLabels")))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Data summary",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="item",
                        `title`="Item",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text")),
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "showLabels")))
            self$add(jmvcore::Html$new(
                options=options,
                name="warnings",
                title="Data handling warnings",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "showLabels")))
            self$add(jmvcore::Image$new(
                options=options,
                name="dendrogram",
                title="Group-average cluster dendrogram",
                visible=FALSE,
                width=650,
                height=480,
                renderFun=".plotDendrogram",
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "showLabels")))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="How to read this dendrogram",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "showLabels")))
            self$add(jmvcore::Table$new(
                options=options,
                name="settings",
                title="Analysis settings",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="setting",
                        `title`="Setting",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text")),
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "showLabels")))}))

clusterBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clusterBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tofu",
                name = "cluster",
                version = c(0,2,0),
                options = options,
                results = clusterResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Cluster analysis
#'
#'
#' @param data .
#' @param vars .
#' @param labels .
#' @param transform .
#' @param distance .
#' @param showLabels .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$guidance} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dendrogram} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$settings} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
cluster <- function(
    data,
    vars,
    labels = NULL,
    transform = "none",
    distance = "bray",
    showLabels = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cluster requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(labels), labels, NULL))


    options <- clusterOptions$new(
        vars = vars,
        labels = labels,
        transform = transform,
        distance = distance,
        showLabels = showLabels)

    analysis <- clusterClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
