
# This file is automatically generated, you probably don't want to edit this

clusterOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clusterOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            labels = NULL,
            transform = "none",
            distance = "bray",
            sampleLabels = "auto",
            showLabels = "__tofu_unset__",
            defineClusters = FALSE,
            cutMode = "number",
            numberClusters = 3,
            cutHeight = 0.5, ...) {

            super$initialize(
                package="tofu",
                name="cluster",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "nominal",
                    "ordinal",
                    "id"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                default=NULL)
            private$..transform <- jmvcore::OptionList$new(
                "transform",
                transform,
                options=list(
                    "none",
                    "sqrt",
                    "fourthroot",
                    "log",
                    "pa",
                    "wisconsin",
                    "hellinger",
                    "total",
                    "max",
                    "frequency",
                    "normalize",
                    "range",
                    "standardize",
                    "chi.square",
                    "rclr"),
                default="none")
            private$..distance <- jmvcore::OptionList$new(
                "distance",
                distance,
                options=list(
                    "bray",
                    "jaccard",
                    "euclidean",
                    "manhattan",
                    "canberra",
                    "kulczynski",
                    "gower",
                    "morisita",
                    "horn",
                    "mountford",
                    "raup",
                    "binomial",
                    "chao",
                    "cao",
                    "clark",
                    "altGower",
                    "mahalanobis"),
                default="bray")
            private$..sampleLabels <- jmvcore::OptionList$new(
                "sampleLabels",
                sampleLabels,
                options=list(
                    "auto",
                    "show",
                    "hide"),
                default="auto")
            private$..showLabels <- jmvcore::OptionString$new(
                "showLabels",
                showLabels,
                default="__tofu_unset__",
                hidden=TRUE)
            private$..defineClusters <- jmvcore::OptionBool$new(
                "defineClusters",
                defineClusters,
                default=FALSE)
            private$..cutMode <- jmvcore::OptionList$new(
                "cutMode",
                cutMode,
                options=list(
                    "number",
                    "height"),
                default="number")
            private$..numberClusters <- jmvcore::OptionNumber$new(
                "numberClusters",
                numberClusters,
                default=3,
                min=2)
            private$..cutHeight <- jmvcore::OptionNumber$new(
                "cutHeight",
                cutHeight,
                default=0.5,
                min=0)

            self$.addOption(private$..vars)
            self$.addOption(private$..labels)
            self$.addOption(private$..transform)
            self$.addOption(private$..distance)
            self$.addOption(private$..sampleLabels)
            self$.addOption(private$..showLabels)
            self$.addOption(private$..defineClusters)
            self$.addOption(private$..cutMode)
            self$.addOption(private$..numberClusters)
            self$.addOption(private$..cutHeight)
        }),
    active = list(
        vars = function() private$..vars$value,
        labels = function() private$..labels$value,
        transform = function() private$..transform$value,
        distance = function() private$..distance$value,
        sampleLabels = function() private$..sampleLabels$value,
        showLabels = function() private$..showLabels$value,
        defineClusters = function() private$..defineClusters$value,
        cutMode = function() private$..cutMode$value,
        numberClusters = function() private$..numberClusters$value,
        cutHeight = function() private$..cutHeight$value),
    private = list(
        ..vars = NA,
        ..labels = NA,
        ..transform = NA,
        ..distance = NA,
        ..sampleLabels = NA,
        ..showLabels = NA,
        ..defineClusters = NA,
        ..cutMode = NA,
        ..numberClusters = NA,
        ..cutHeight = NA)
)

clusterResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clusterResults",
    inherit = jmvcore::Group,
    active = list(
        guidance = function() private$.items[["guidance"]],
        summary = function() private$.items[["summary"]],
        warnings = function() private$.items[["warnings"]],
        dendrogram = function() private$.items[["dendrogram"]],
        dendrogramDescription = function() private$.items[["dendrogramDescription"]],
        dendrogramStructure = function() private$.items[["dendrogramStructure"]],
        membership = function() private$.items[["membership"]],
        interpretation = function() private$.items[["interpretation"]],
        settings = function() private$.items[["settings"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Cluster analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="guidance",
                title="Getting started",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "sampleLabels",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Data summary",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="item",
                        `title`="Item",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text")),
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "sampleLabels",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Html$new(
                options=options,
                name="warnings",
                title="Data handling warnings",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "sampleLabels",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Image$new(
                options=options,
                name="dendrogram",
                title="Group-average cluster dendrogram",
                visible=FALSE,
                width=600,
                height=500,
                renderFun=".plotDendrogram",
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "sampleLabels",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Html$new(
                options=options,
                name="dendrogramDescription",
                title="Plot details",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "sampleLabels",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Table$new(
                options=options,
                name="dendrogramStructure",
                title="Dendrogram structure",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="recordType",
                        `title`="Record",
                        `type`="text"),
                    list(
                        `name`="displayOrder",
                        `title`="Display order",
                        `type`="integer"),
                    list(
                        `name`="sample",
                        `title`="Sample",
                        `type`="text"),
                    list(
                        `name`="mergeStep",
                        `title`="Merge step",
                        `type`="integer"),
                    list(
                        `name`="leftChild",
                        `title`="Left child",
                        `type`="text"),
                    list(
                        `name`="rightChild",
                        `title`="Right child",
                        `type`="text"),
                    list(
                        `name`="height",
                        `title`="Height",
                        `type`="number")),
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "sampleLabels",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Table$new(
                options=options,
                name="membership",
                title="Cluster membership",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="sample",
                        `title`="Sample",
                        `type`="text"),
                    list(
                        `name`="cluster",
                        `title`="Cluster",
                        `type`="integer")),
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="How to read this dendrogram",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "sampleLabels",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Table$new(
                options=options,
                name="settings",
                title="Analysis settings",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="setting",
                        `title`="Setting",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text")),
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "sampleLabels",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))}))

clusterBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clusterBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tofu",
                name = "cluster",
                version = c(0,2,0),
                options = options,
                results = clusterResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Cluster analysis
#'
#'
#' @param data .
#' @param vars .
#' @param labels .
#' @param transform .
#' @param distance .
#' @param sampleLabels .
#' @param showLabels Compatibility value for analyses saved before sample
#'   label modes were introduced.
#' @param defineClusters .
#' @param cutMode .
#' @param numberClusters .
#' @param cutHeight .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$guidance} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dendrogram} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$dendrogramDescription} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dendrogramStructure} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$membership} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$settings} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
cluster <- function(
    data,
    vars,
    labels = NULL,
    transform = "none",
    distance = "bray",
    sampleLabels = "auto",
    showLabels = "__tofu_unset__",
    defineClusters = FALSE,
    cutMode = "number",
    numberClusters = 3,
    cutHeight = 0.5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cluster requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(labels), labels, NULL))


    options <- clusterOptions$new(
        vars = vars,
        labels = labels,
        transform = transform,
        distance = distance,
        sampleLabels = sampleLabels,
        showLabels = showLabels,
        defineClusters = defineClusters,
        cutMode = cutMode,
        numberClusters = numberClusters,
        cutHeight = cutHeight)

    analysis <- clusterClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
