
# This file is automatically generated, you probably don't want to edit this

clusterOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clusterOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            labels = NULL,
            contextVars = list(),
            showSampleOrder = FALSE,
            showMergeHistory = FALSE,
            transform = "none",
            distance = "bray",
            sampleLabels = "auto",
            showLabels = "__miso_unset__",
            defineClusters = FALSE,
            cutMode = "number",
            numberClusters = 3,
            cutHeight = 0.5, ...) {

            super$initialize(
                package="miso",
                name="cluster",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "nominal",
                    "ordinal",
                    "id"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                default=NULL)
            private$..contextVars <- jmvcore::OptionVariables$new(
                "contextVars",
                contextVars,
                suggested=list(
                    "nominal",
                    "ordinal",
                    "id"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                default=list())
            private$..showSampleOrder <- jmvcore::OptionBool$new(
                "showSampleOrder",
                showSampleOrder,
                default=FALSE)
            private$..showMergeHistory <- jmvcore::OptionBool$new(
                "showMergeHistory",
                showMergeHistory,
                default=FALSE)
            private$..transform <- jmvcore::OptionList$new(
                "transform",
                transform,
                options=list(
                    "none",
                    "sqrt",
                    "fourthroot",
                    "log",
                    "pa",
                    "wisconsin",
                    "hellinger",
                    "total",
                    "max",
                    "frequency",
                    "normalize",
                    "range",
                    "standardize",
                    "chi.square",
                    "rclr"),
                default="none")
            private$..distance <- jmvcore::OptionList$new(
                "distance",
                distance,
                options=list(
                    "bray",
                    "jaccard",
                    "euclidean",
                    "manhattan",
                    "canberra",
                    "kulczynski",
                    "gower",
                    "morisita",
                    "horn",
                    "mountford",
                    "raup",
                    "binomial",
                    "chao",
                    "cao",
                    "clark",
                    "altGower",
                    "mahalanobis"),
                default="bray")
            private$..sampleLabels <- jmvcore::OptionList$new(
                "sampleLabels",
                sampleLabels,
                options=list(
                    "auto",
                    "show",
                    "hide"),
                default="auto")
            private$..showLabels <- jmvcore::OptionString$new(
                "showLabels",
                showLabels,
                default="__miso_unset__",
                hidden=TRUE)
            private$..defineClusters <- jmvcore::OptionBool$new(
                "defineClusters",
                defineClusters,
                default=FALSE)
            private$..cutMode <- jmvcore::OptionList$new(
                "cutMode",
                cutMode,
                options=list(
                    "number",
                    "height"),
                default="number")
            private$..numberClusters <- jmvcore::OptionNumber$new(
                "numberClusters",
                numberClusters,
                default=3,
                min=2)
            private$..cutHeight <- jmvcore::OptionNumber$new(
                "cutHeight",
                cutHeight,
                default=0.5,
                min=0)

            self$.addOption(private$..vars)
            self$.addOption(private$..labels)
            self$.addOption(private$..contextVars)
            self$.addOption(private$..showSampleOrder)
            self$.addOption(private$..showMergeHistory)
            self$.addOption(private$..transform)
            self$.addOption(private$..distance)
            self$.addOption(private$..sampleLabels)
            self$.addOption(private$..showLabels)
            self$.addOption(private$..defineClusters)
            self$.addOption(private$..cutMode)
            self$.addOption(private$..numberClusters)
            self$.addOption(private$..cutHeight)
        }),
    active = list(
        vars = function() private$..vars$value,
        labels = function() private$..labels$value,
        contextVars = function() private$..contextVars$value,
        showSampleOrder = function() private$..showSampleOrder$value,
        showMergeHistory = function() private$..showMergeHistory$value,
        transform = function() private$..transform$value,
        distance = function() private$..distance$value,
        sampleLabels = function() private$..sampleLabels$value,
        showLabels = function() private$..showLabels$value,
        defineClusters = function() private$..defineClusters$value,
        cutMode = function() private$..cutMode$value,
        numberClusters = function() private$..numberClusters$value,
        cutHeight = function() private$..cutHeight$value),
    private = list(
        ..vars = NA,
        ..labels = NA,
        ..contextVars = NA,
        ..showSampleOrder = NA,
        ..showMergeHistory = NA,
        ..transform = NA,
        ..distance = NA,
        ..sampleLabels = NA,
        ..showLabels = NA,
        ..defineClusters = NA,
        ..cutMode = NA,
        ..numberClusters = NA,
        ..cutHeight = NA)
)

clusterResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clusterResults",
    inherit = jmvcore::Group,
    active = list(
        guidance = function() private$.items[["guidance"]],
        warnings = function() private$.items[["warnings"]],
        dendrogramDescription = function() private$.items[["dendrogramDescription"]],
        dendrogram = function() private$.items[["dendrogram"]],
        membership = function() private$.items[["membership"]],
        sampleOrder = function() private$.items[["sampleOrder"]],
        mergeHistory = function() private$.items[["mergeHistory"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Cluster analysis",
                refs=list(
                    "vegan"))
            self$add(jmvcore::Html$new(
                options=options,
                name="guidance",
                title="Getting Started",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Html$new(
                options=options,
                name="warnings",
                title="",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Html$new(
                options=options,
                name="dendrogramDescription",
                title="Group-average Cluster Dendrogram",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Image$new(
                options=options,
                name="dendrogram",
                title="Cluster Dendrogram",
                visible=FALSE,
                width=600,
                height=500,
                renderFun=".plotDendrogram",
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Table$new(
                options=options,
                name="membership",
                title="Cluster Membership",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="sample",
                        `title`="Sample",
                        `type`="text"),
                    list(
                        `name`="cluster",
                        `title`="Cluster",
                        `type`="integer")),
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Table$new(
                options=options,
                name="sampleOrder",
                title="Sample Order",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="position",
                        `title`="Position",
                        `type`="integer"),
                    list(
                        `name`="sample",
                        `title`="Sample",
                        `type`="text")),
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))
            self$add(jmvcore::Table$new(
                options=options,
                name="mergeHistory",
                title="Merge History",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="step",
                        `title`="Step",
                        `type`="integer"),
                    list(
                        `name`="first",
                        `title`="First sample or branch",
                        `type`="text"),
                    list(
                        `name`="second",
                        `title`="Second sample or branch",
                        `type`="text"),
                    list(
                        `name`="height",
                        `title`="Dissimilarity at merge",
                        `type`="number")),
                clearWith=list(
                    "vars",
                    "labels",
                    "transform",
                    "distance",
                    "defineClusters",
                    "cutMode",
                    "numberClusters",
                    "cutHeight")))}))

clusterBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clusterBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "miso",
                name = "cluster",
                version = c(1,0,0),
                options = options,
                results = clusterResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Cluster analysis
#'
#' Groups samples by hierarchical clustering of dissimilarities calculated
#' with vegan::vegdist and stats::hclust. The dendrogram and optional cluster
#' memberships are descriptive.
#' @section References:
#' Oksanen et al. (2026). vegan: Community Ecology Package (R package version 2.7-5). https://vegandevs.github.io/vegan/
#'
#' @param data .
#' @param vars .
#' @param labels .
#' @param contextVars .
#' @param showSampleOrder .
#' @param showMergeHistory .
#' @param transform .
#' @param distance .
#' @param sampleLabels .
#' @param showLabels Compatibility value for analyses saved before sample
#'   label modes were introduced.
#' @param defineClusters .
#' @param cutMode .
#' @param numberClusters .
#' @param cutHeight .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$guidance} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dendrogramDescription} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dendrogram} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$membership} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sampleOrder} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mergeHistory} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$membership$asDF}
#'
#' \code{as.data.frame(results$membership)}
#'
#' @export
cluster <- function(
    data,
    vars,
    labels = NULL,
    contextVars = list(),
    showSampleOrder = FALSE,
    showMergeHistory = FALSE,
    transform = "none",
    distance = "bray",
    sampleLabels = "auto",
    showLabels = "__miso_unset__",
    defineClusters = FALSE,
    cutMode = "number",
    numberClusters = 3,
    cutHeight = 0.5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cluster requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(contextVars)) contextVars <- jmvcore::resolveQuo(jmvcore::enquo(contextVars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(contextVars), contextVars, NULL))


    options <- clusterOptions$new(
        vars = vars,
        labels = labels,
        contextVars = contextVars,
        showSampleOrder = showSampleOrder,
        showMergeHistory = showMergeHistory,
        transform = transform,
        distance = distance,
        sampleLabels = sampleLabels,
        showLabels = showLabels,
        defineClusters = defineClusters,
        cutMode = cutMode,
        numberClusters = numberClusters,
        cutHeight = cutHeight)

    analysis <- clusterClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
