
# This file is automatically generated, you probably don't want to edit this

nmdsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "nmdsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            factor = NULL,
            transform = "none",
            distance = "bray",
            distBinary = FALSE,
            seed = 0,
            nmdsK = 2,
            nmdsTrymax = 20,
            nmdsMaxit = 200,
            nmdsShepard = TRUE,
            nmdsOverlay = TRUE,
            nmdsEnv = NULL,
            nmdsSpecies = FALSE,
            nmdsHull = FALSE,
            nmdsEllipse = FALSE,
            nmdsSpider = FALSE,
            nmdsEnvPerm = 99, ...) {

            super$initialize(
                package="miso",
                name="nmds",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..factor <- jmvcore::OptionVariable$new(
                "factor",
                factor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..transform <- jmvcore::OptionList$new(
                "transform",
                transform,
                options=list(
                    "none",
                    "sqrt",
                    "fourthroot",
                    "log",
                    "pa",
                    "wisconsin",
                    "hellinger",
                    "total",
                    "max",
                    "frequency",
                    "normalize",
                    "range",
                    "standardize",
                    "chi.square",
                    "rclr"),
                default="none")
            private$..distance <- jmvcore::OptionList$new(
                "distance",
                distance,
                options=list(
                    "bray",
                    "jaccard",
                    "euclidean",
                    "manhattan",
                    "canberra",
                    "kulczynski",
                    "gower",
                    "morisita",
                    "horn",
                    "mountford",
                    "raup",
                    "binomial",
                    "chao",
                    "cao",
                    "clark",
                    "altGower",
                    "mahalanobis"),
                default="bray")
            private$..distBinary <- jmvcore::OptionBool$new(
                "distBinary",
                distBinary,
                default=FALSE,
                hidden=TRUE)
            private$..seed <- jmvcore::OptionNumber$new(
                "seed",
                seed,
                default=0,
                min=0)
            private$..nmdsK <- jmvcore::OptionNumber$new(
                "nmdsK",
                nmdsK,
                default=2,
                min=2,
                max=3,
                hidden=TRUE)
            private$..nmdsTrymax <- jmvcore::OptionNumber$new(
                "nmdsTrymax",
                nmdsTrymax,
                default=20,
                min=1)
            private$..nmdsMaxit <- jmvcore::OptionNumber$new(
                "nmdsMaxit",
                nmdsMaxit,
                default=200,
                min=1)
            private$..nmdsShepard <- jmvcore::OptionBool$new(
                "nmdsShepard",
                nmdsShepard,
                default=TRUE)
            private$..nmdsOverlay <- jmvcore::OptionBool$new(
                "nmdsOverlay",
                nmdsOverlay,
                default=TRUE)
            private$..nmdsEnv <- jmvcore::OptionVariables$new(
                "nmdsEnv",
                nmdsEnv,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..nmdsSpecies <- jmvcore::OptionBool$new(
                "nmdsSpecies",
                nmdsSpecies,
                default=FALSE)
            private$..nmdsHull <- jmvcore::OptionBool$new(
                "nmdsHull",
                nmdsHull,
                default=FALSE)
            private$..nmdsEllipse <- jmvcore::OptionBool$new(
                "nmdsEllipse",
                nmdsEllipse,
                default=FALSE)
            private$..nmdsSpider <- jmvcore::OptionBool$new(
                "nmdsSpider",
                nmdsSpider,
                default=FALSE)
            private$..nmdsEnvPerm <- jmvcore::OptionNumber$new(
                "nmdsEnvPerm",
                nmdsEnvPerm,
                default=99,
                min=1)

            self$.addOption(private$..vars)
            self$.addOption(private$..factor)
            self$.addOption(private$..transform)
            self$.addOption(private$..distance)
            self$.addOption(private$..distBinary)
            self$.addOption(private$..seed)
            self$.addOption(private$..nmdsK)
            self$.addOption(private$..nmdsTrymax)
            self$.addOption(private$..nmdsMaxit)
            self$.addOption(private$..nmdsShepard)
            self$.addOption(private$..nmdsOverlay)
            self$.addOption(private$..nmdsEnv)
            self$.addOption(private$..nmdsSpecies)
            self$.addOption(private$..nmdsHull)
            self$.addOption(private$..nmdsEllipse)
            self$.addOption(private$..nmdsSpider)
            self$.addOption(private$..nmdsEnvPerm)
        }),
    active = list(
        vars = function() private$..vars$value,
        factor = function() private$..factor$value,
        transform = function() private$..transform$value,
        distance = function() private$..distance$value,
        distBinary = function() private$..distBinary$value,
        seed = function() private$..seed$value,
        nmdsK = function() private$..nmdsK$value,
        nmdsTrymax = function() private$..nmdsTrymax$value,
        nmdsMaxit = function() private$..nmdsMaxit$value,
        nmdsShepard = function() private$..nmdsShepard$value,
        nmdsOverlay = function() private$..nmdsOverlay$value,
        nmdsEnv = function() private$..nmdsEnv$value,
        nmdsSpecies = function() private$..nmdsSpecies$value,
        nmdsHull = function() private$..nmdsHull$value,
        nmdsEllipse = function() private$..nmdsEllipse$value,
        nmdsSpider = function() private$..nmdsSpider$value,
        nmdsEnvPerm = function() private$..nmdsEnvPerm$value),
    private = list(
        ..vars = NA,
        ..factor = NA,
        ..transform = NA,
        ..distance = NA,
        ..distBinary = NA,
        ..seed = NA,
        ..nmdsK = NA,
        ..nmdsTrymax = NA,
        ..nmdsMaxit = NA,
        ..nmdsShepard = NA,
        ..nmdsOverlay = NA,
        ..nmdsEnv = NA,
        ..nmdsSpecies = NA,
        ..nmdsHull = NA,
        ..nmdsEllipse = NA,
        ..nmdsSpider = NA,
        ..nmdsEnvPerm = NA)
)

nmdsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "nmdsResults",
    inherit = jmvcore::Group,
    active = list(
        guidance = function() private$.items[["guidance"]],
        warnings = function() private$.items[["warnings"]],
        ordinationDescription = function() private$.items[["ordinationDescription"]],
        ordination = function() private$.items[["ordination"]],
        sites = function() private$.items[["sites"]],
        stress = function() private$.items[["stress"]],
        shepardDescription = function() private$.items[["shepardDescription"]],
        shepard = function() private$.items[["shepard"]],
        shepardPairs = function() private$.items[["shepardPairs"]],
        envfit = function() private$.items[["envfit"]],
        features = function() private$.items[["features"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="nMDS",
                refs=list(
                    "vegan"))
            self$add(jmvcore::Html$new(
                options=options,
                name="guidance",
                title="Getting Started",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "seed",
                    "nmdsK",
                    "nmdsTrymax",
                    "nmdsMaxit",
                    "nmdsEnv",
                    "nmdsEnvPerm")))
            self$add(jmvcore::Html$new(
                options=options,
                name="warnings",
                title="",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "seed",
                    "nmdsK",
                    "nmdsTrymax",
                    "nmdsMaxit",
                    "nmdsEnv",
                    "nmdsEnvPerm")))
            self$add(jmvcore::Html$new(
                options=options,
                name="ordinationDescription",
                title="Two-dimensional nMDS ordination",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "seed",
                    "nmdsK",
                    "nmdsTrymax",
                    "nmdsMaxit",
                    "nmdsEnv",
                    "nmdsEnvPerm")))
            self$add(jmvcore::Image$new(
                options=options,
                name="ordination",
                title="nMDS Ordination",
                width=580,
                height=450,
                renderFun=".plotNmds",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "seed",
                    "nmdsK",
                    "nmdsTrymax",
                    "nmdsMaxit",
                    "nmdsEnv",
                    "nmdsEnvPerm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="sites",
                title="Site Scores",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="row",
                        `title`="Row",
                        `type`="integer"),
                    list(
                        `name`="NMDS1",
                        `title`="NMDS1",
                        `type`="number",
                        `format`="zto"),
                    list(
                        `name`="NMDS2",
                        `title`="NMDS2",
                        `type`="number",
                        `format`="zto"),
                    list(
                        `name`="NMDS3",
                        `title`="NMDS3",
                        `type`="number",
                        `format`="zto"),
                    list(
                        `name`="group",
                        `title`="Group",
                        `type`="text")),
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "seed",
                    "nmdsK",
                    "nmdsTrymax",
                    "nmdsMaxit",
                    "nmdsEnv",
                    "nmdsEnvPerm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="stress",
                title="Stress and Convergence Diagnostics",
                rows=8,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="item",
                        `title`="Item",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text")),
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "seed",
                    "nmdsK",
                    "nmdsTrymax",
                    "nmdsMaxit",
                    "nmdsEnv",
                    "nmdsEnvPerm")))
            self$add(jmvcore::Html$new(
                options=options,
                name="shepardDescription",
                title="Shepard Diagram",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "seed",
                    "nmdsK",
                    "nmdsTrymax",
                    "nmdsMaxit",
                    "nmdsEnv",
                    "nmdsEnvPerm")))
            self$add(jmvcore::Image$new(
                options=options,
                name="shepard",
                title="Shepard Diagram",
                width=580,
                height=450,
                renderFun=".plotShepard",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "seed",
                    "nmdsK",
                    "nmdsTrymax",
                    "nmdsMaxit",
                    "nmdsEnv",
                    "nmdsEnvPerm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="shepardPairs",
                title="Shepard Diagram Values",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="dissimilarity",
                        `title`="Observed dissimilarity",
                        `type`="number",
                        `format`="zto"),
                    list(
                        `name`="ordinationDistance",
                        `title`="Ordination distance",
                        `type`="number",
                        `format`="zto"),
                    list(
                        `name`="monotonicFit",
                        `title`="Monotone fitted distance",
                        `type`="number",
                        `format`="zto")),
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "seed",
                    "nmdsK",
                    "nmdsTrymax",
                    "nmdsMaxit",
                    "nmdsEnv",
                    "nmdsEnvPerm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="envfit",
                title="Environmental Fit",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="variable",
                        `title`="Variable",
                        `type`="text"),
                    list(
                        `name`="r2",
                        `title`="r\u00B2",
                        `type`="number",
                        `format`="zto"),
                    list(
                        `name`="p",
                        `title`="p (unadjusted)",
                        `type`="number",
                        `format`="zto,pvalue"),
                    list(
                        `name`="samples",
                        `title`="n",
                        `type`="integer"),
                    list(
                        `name`="permutations",
                        `title`="Permutations",
                        `type`="integer"),
                    list(
                        `name`="NMDS1",
                        `title`="NMDS1",
                        `type`="number",
                        `format`="zto"),
                    list(
                        `name`="NMDS2",
                        `title`="NMDS2",
                        `type`="number",
                        `format`="zto"),
                    list(
                        `name`="NMDS3",
                        `title`="NMDS3",
                        `type`="number",
                        `format`="zto")),
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "seed",
                    "nmdsK",
                    "nmdsTrymax",
                    "nmdsMaxit",
                    "nmdsEnv",
                    "nmdsEnvPerm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="features",
                title="Feature Scores",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="feature",
                        `title`="Feature",
                        `type`="text"),
                    list(
                        `name`="NMDS1",
                        `title`="NMDS1",
                        `type`="number",
                        `format`="zto"),
                    list(
                        `name`="NMDS2",
                        `title`="NMDS2",
                        `type`="number",
                        `format`="zto"),
                    list(
                        `name`="NMDS3",
                        `title`="NMDS3",
                        `type`="number",
                        `format`="zto")),
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "seed",
                    "nmdsK",
                    "nmdsTrymax",
                    "nmdsMaxit",
                    "nmdsEnv",
                    "nmdsEnvPerm")))}))

nmdsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "nmdsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "miso",
                name = "nmds",
                version = c(1,0,0),
                options = options,
                results = nmdsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' nMDS
#'
#' Produces a non-metric multidimensional scaling ordination through
#' vegan::metaMDS. Reports stress and convergence and can add group, feature,
#' environmental, and Shepard diagnostics.
#' @section References:
#' Oksanen et al. (2026). vegan: Community Ecology Package (R package version 2.7-5). https://vegandevs.github.io/vegan/
#'
#' @param data .
#' @param vars .
#' @param factor .
#' @param transform .
#' @param distance .
#' @param distBinary .
#' @param seed .
#' @param nmdsK .
#' @param nmdsTrymax .
#' @param nmdsMaxit .
#' @param nmdsShepard .
#' @param nmdsOverlay .
#' @param nmdsEnv .
#' @param nmdsSpecies .
#' @param nmdsHull .
#' @param nmdsEllipse .
#' @param nmdsSpider .
#' @param nmdsEnvPerm .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$guidance} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ordinationDescription} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ordination} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$sites} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$stress} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$shepardDescription} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$shepard} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$shepardPairs} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$envfit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$features} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$sites$asDF}
#'
#' \code{as.data.frame(results$sites)}
#'
#' @export
nmds <- function(
    data,
    vars,
    factor = NULL,
    transform = "none",
    distance = "bray",
    distBinary = FALSE,
    seed = 0,
    nmdsK = 2,
    nmdsTrymax = 20,
    nmdsMaxit = 200,
    nmdsShepard = TRUE,
    nmdsOverlay = TRUE,
    nmdsEnv = NULL,
    nmdsSpecies = FALSE,
    nmdsHull = FALSE,
    nmdsEllipse = FALSE,
    nmdsSpider = FALSE,
    nmdsEnvPerm = 99) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("nmds requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(factor)) factor <- jmvcore::resolveQuo(jmvcore::enquo(factor))
    if ( ! missing(nmdsEnv)) nmdsEnv <- jmvcore::resolveQuo(jmvcore::enquo(nmdsEnv))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(factor), factor, NULL),
            `if`( ! missing(nmdsEnv), nmdsEnv, NULL))

    for (v in factor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- nmdsOptions$new(
        vars = vars,
        factor = factor,
        transform = transform,
        distance = distance,
        distBinary = distBinary,
        seed = seed,
        nmdsK = nmdsK,
        nmdsTrymax = nmdsTrymax,
        nmdsMaxit = nmdsMaxit,
        nmdsShepard = nmdsShepard,
        nmdsOverlay = nmdsOverlay,
        nmdsEnv = nmdsEnv,
        nmdsSpecies = nmdsSpecies,
        nmdsHull = nmdsHull,
        nmdsEllipse = nmdsEllipse,
        nmdsSpider = nmdsSpider,
        nmdsEnvPerm = nmdsEnvPerm)

    analysis <- nmdsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
