
# This file is automatically generated, you probably don't want to edit this

pcoaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pcoaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            factor = NULL,
            transform = "none",
            distance = "bray",
            distBinary = FALSE,
            sqrtDist = FALSE,
            correction = "none",
            showCentroids = FALSE,
            showSpiders = FALSE, ...) {

            super$initialize(
                package="miso",
                name="pcoa",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..factor <- jmvcore::OptionVariable$new(
                "factor",
                factor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..transform <- jmvcore::OptionList$new(
                "transform",
                transform,
                options=list(
                    "none",
                    "sqrt",
                    "fourthroot",
                    "log",
                    "pa",
                    "wisconsin",
                    "hellinger",
                    "total",
                    "max",
                    "frequency",
                    "normalize",
                    "range",
                    "standardize",
                    "chi.square",
                    "rclr"),
                default="none")
            private$..distance <- jmvcore::OptionList$new(
                "distance",
                distance,
                options=list(
                    "bray",
                    "jaccard",
                    "euclidean",
                    "manhattan",
                    "canberra",
                    "kulczynski",
                    "gower",
                    "morisita",
                    "horn",
                    "mountford",
                    "raup",
                    "binomial",
                    "chao",
                    "cao",
                    "clark",
                    "altGower",
                    "mahalanobis"),
                default="bray")
            private$..distBinary <- jmvcore::OptionBool$new(
                "distBinary",
                distBinary,
                default=FALSE)
            private$..sqrtDist <- jmvcore::OptionBool$new(
                "sqrtDist",
                sqrtDist,
                default=FALSE)
            private$..correction <- jmvcore::OptionList$new(
                "correction",
                correction,
                options=list(
                    "none",
                    "lingoes",
                    "cailliez"),
                default="none")
            private$..showCentroids <- jmvcore::OptionBool$new(
                "showCentroids",
                showCentroids,
                default=FALSE)
            private$..showSpiders <- jmvcore::OptionBool$new(
                "showSpiders",
                showSpiders,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..factor)
            self$.addOption(private$..transform)
            self$.addOption(private$..distance)
            self$.addOption(private$..distBinary)
            self$.addOption(private$..sqrtDist)
            self$.addOption(private$..correction)
            self$.addOption(private$..showCentroids)
            self$.addOption(private$..showSpiders)
        }),
    active = list(
        vars = function() private$..vars$value,
        factor = function() private$..factor$value,
        transform = function() private$..transform$value,
        distance = function() private$..distance$value,
        distBinary = function() private$..distBinary$value,
        sqrtDist = function() private$..sqrtDist$value,
        correction = function() private$..correction$value,
        showCentroids = function() private$..showCentroids$value,
        showSpiders = function() private$..showSpiders$value),
    private = list(
        ..vars = NA,
        ..factor = NA,
        ..transform = NA,
        ..distance = NA,
        ..distBinary = NA,
        ..sqrtDist = NA,
        ..correction = NA,
        ..showCentroids = NA,
        ..showSpiders = NA)
)

pcoaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pcoaResults",
    inherit = jmvcore::Group,
    active = list(
        guidance = function() private$.items[["guidance"]],
        warnings = function() private$.items[["warnings"]],
        ordinationDescription = function() private$.items[["ordinationDescription"]],
        ordination = function() private$.items[["ordination"]],
        sites = function() private$.items[["sites"]],
        centroids = function() private$.items[["centroids"]],
        eigenvalues = function() private$.items[["eigenvalues"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="PCoA",
                refs=list(
                    "vegan"))
            self$add(jmvcore::Html$new(
                options=options,
                name="guidance",
                title="Getting Started",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "sqrtDist",
                    "correction")))
            self$add(jmvcore::Html$new(
                options=options,
                name="warnings",
                title="",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "sqrtDist",
                    "correction")))
            self$add(jmvcore::Html$new(
                options=options,
                name="ordinationDescription",
                title="Principal coordinates ordination",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "sqrtDist",
                    "correction")))
            self$add(jmvcore::Image$new(
                options=options,
                name="ordination",
                title="PCoA Ordination",
                width=600,
                height=500,
                renderFun=".plotPcoa",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "sqrtDist",
                    "correction")))
            self$add(jmvcore::Table$new(
                options=options,
                name="sites",
                title="Site Coordinates",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="site", 
                        `title`="Site", 
                        `type`="text"),
                    list(
                        `name`="sourceRow", 
                        `title`="Source row", 
                        `type`="integer"),
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="PCoA1", 
                        `title`="PCoA1", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="PCoA2", 
                        `title`="PCoA2", 
                        `type`="number", 
                        `format`="zto")),
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "sqrtDist",
                    "correction")))
            self$add(jmvcore::Table$new(
                options=options,
                name="centroids",
                title="Group Centroids",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="PCoA1", 
                        `title`="PCoA1", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="PCoA2", 
                        `title`="PCoA2", 
                        `type`="number", 
                        `format`="zto")),
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "sqrtDist",
                    "correction")))
            self$add(jmvcore::Table$new(
                options=options,
                name="eigenvalues",
                title="Eigenvalues",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="axis", 
                        `title`="Axis", 
                        `type`="text"),
                    list(
                        `name`="eigenvalue", 
                        `title`="Eigenvalue", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="sign", 
                        `title`="Sign", 
                        `type`="text"),
                    list(
                        `name`="explained", 
                        `title`="Explained (%)", 
                        `type`="number", 
                        `format`="zto")),
                clearWith=list(
                    "vars",
                    "factor",
                    "transform",
                    "distance",
                    "distBinary",
                    "sqrtDist",
                    "correction")))}))

pcoaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pcoaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "miso",
                name = "pcoa",
                version = c(1,0,0),
                options = options,
                results = pcoaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' PCoA
#'
#' Performs descriptive principal coordinates analysis (PCoA) of pairwise 
#' dissimilarities among sites. The ordination visualises resemblance 
#' structure and does not test group differences. When called from R, it 
#' returns the jamovi analysis results object.
#' @section References:
#' Oksanen et al. (2026). vegan: Community Ecology Package (R package version 2.7-5). https://vegandevs.github.io/vegan/
#'
#' @param data The data frame containing the feature and grouping variables.
#' @param vars Two or more numeric feature variables used to calculate
#'   dissimilarities among sites.
#' @param factor An optional factor used to identify groups in the plot and
#'   centroid table.
#' @param transform The transformation applied before calculating
#'   dissimilarities; one of \code{none}, \code{sqrt}, \code{fourthroot},
#'   \code{log}, \code{pa}, \code{wisconsin}, \code{hellinger}, \code{total},
#'   \code{max}, \code{frequency}, \code{normalize}, \code{range},
#'   \code{standardize}, \code{chi.square}, or \code{rclr}.
#' @param distance The dissimilarity index; one of \code{bray},
#'   \code{jaccard}, \code{euclidean}, \code{manhattan}, \code{canberra},
#'   \code{kulczynski}, \code{gower}, \code{morisita}, \code{horn},
#'   \code{mountford}, \code{raup}, \code{binomial}, \code{chao}, \code{cao},
#'   \code{clark}, \code{altGower}, or \code{mahalanobis}.
#' @param distBinary Whether to convert feature values to presence or absence
#'   when calculating dissimilarities.
#' @param sqrtDist Whether to square-root the calculated dissimilarities
#'   before ordination.
#' @param correction The additive correction for negative eigenvalues; one of
#'   \code{none}, \code{lingoes}, or \code{cailliez}.
#' @param showCentroids Whether to draw group centroids when a grouping
#'   variable is selected.
#' @param showSpiders Whether to connect each site to its group centroid;
#'   enabling spiders also draws the centroids.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$guidance} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ordinationDescription} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ordination} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$sites} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centroids} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$eigenvalues} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$sites$asDF}
#'
#' \code{as.data.frame(results$sites)}
#'
#' @export
pcoa <- function(
    data,
    vars,
    factor = NULL,
    transform = "none",
    distance = "bray",
    distBinary = FALSE,
    sqrtDist = FALSE,
    correction = "none",
    showCentroids = FALSE,
    showSpiders = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pcoa requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(factor)) factor <- jmvcore::resolveQuo(jmvcore::enquo(factor))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(factor), factor, NULL))

    for (v in factor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- pcoaOptions$new(
        vars = vars,
        factor = factor,
        transform = transform,
        distance = distance,
        distBinary = distBinary,
        sqrtDist = sqrtDist,
        correction = correction,
        showCentroids = showCentroids,
        showSpiders = showSpiders)

    analysis <- pcoaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

