
# This file is automatically generated, you probably don't want to edit this

permdispOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "permdispOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            factor = NULL,
            transform = "none",
            distance = "bray",
            distBinary = FALSE,
            distSqrt = FALSE,
            distAdd = "none",
            seed = 0,
            permN = 999,
            permRestriction = "free",
            permScheme = "free",
            useParallel = FALSE,
            dispType = "median",
            dispBias = FALSE,
            dispPairwise = FALSE,
            dispAdjust = "holm", ...) {

            super$initialize(
                package="tofu",
                name="permdisp",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..factor <- jmvcore::OptionVariable$new(
                "factor",
                factor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..transform <- jmvcore::OptionList$new(
                "transform",
                transform,
                options=list(
                    "none",
                    "sqrt",
                    "fourthroot",
                    "log",
                    "pa",
                    "wisconsin",
                    "hellinger",
                    "total",
                    "max",
                    "frequency",
                    "normalize",
                    "range",
                    "standardize",
                    "chi.square",
                    "rclr"),
                default="none")
            private$..distance <- jmvcore::OptionList$new(
                "distance",
                distance,
                options=list(
                    "bray",
                    "jaccard",
                    "euclidean",
                    "manhattan",
                    "canberra",
                    "kulczynski",
                    "gower",
                    "morisita",
                    "horn",
                    "mountford",
                    "raup",
                    "binomial",
                    "chao",
                    "cao",
                    "clark",
                    "altGower",
                    "mahalanobis"),
                default="bray")
            private$..distBinary <- jmvcore::OptionBool$new(
                "distBinary",
                distBinary,
                default=FALSE)
            private$..distSqrt <- jmvcore::OptionBool$new(
                "distSqrt",
                distSqrt,
                default=FALSE)
            private$..distAdd <- jmvcore::OptionList$new(
                "distAdd",
                distAdd,
                options=list(
                    "none",
                    "cailliez",
                    "lingoes"),
                default="none")
            private$..seed <- jmvcore::OptionNumber$new(
                "seed",
                seed,
                default=0,
                min=0)
            private$..permN <- jmvcore::OptionNumber$new(
                "permN",
                permN,
                default=999,
                min=1)
            private$..permRestriction <- jmvcore::OptionList$new(
                "permRestriction",
                permRestriction,
                options=list(
                    "free",
                    "series"),
                default="free")
            private$..permScheme <- jmvcore::OptionList$new(
                "permScheme",
                permScheme,
                options=list(
                    "free",
                    "stratified",
                    "series"),
                default="free",
                hidden=TRUE)
            private$..useParallel <- jmvcore::OptionBool$new(
                "useParallel",
                useParallel,
                default=FALSE)
            private$..dispType <- jmvcore::OptionList$new(
                "dispType",
                dispType,
                options=list(
                    "median",
                    "centroid"),
                default="median")
            private$..dispBias <- jmvcore::OptionBool$new(
                "dispBias",
                dispBias,
                default=FALSE)
            private$..dispPairwise <- jmvcore::OptionBool$new(
                "dispPairwise",
                dispPairwise,
                default=FALSE)
            private$..dispAdjust <- jmvcore::OptionList$new(
                "dispAdjust",
                dispAdjust,
                options=list(
                    "holm",
                    "bonferroni",
                    "BH",
                    "BY",
                    "none"),
                default="holm")

            self$.addOption(private$..vars)
            self$.addOption(private$..factor)
            self$.addOption(private$..transform)
            self$.addOption(private$..distance)
            self$.addOption(private$..distBinary)
            self$.addOption(private$..distSqrt)
            self$.addOption(private$..distAdd)
            self$.addOption(private$..seed)
            self$.addOption(private$..permN)
            self$.addOption(private$..permRestriction)
            self$.addOption(private$..permScheme)
            self$.addOption(private$..useParallel)
            self$.addOption(private$..dispType)
            self$.addOption(private$..dispBias)
            self$.addOption(private$..dispPairwise)
            self$.addOption(private$..dispAdjust)
        }),
    active = list(
        vars = function() private$..vars$value,
        factor = function() private$..factor$value,
        transform = function() private$..transform$value,
        distance = function() private$..distance$value,
        distBinary = function() private$..distBinary$value,
        distSqrt = function() private$..distSqrt$value,
        distAdd = function() private$..distAdd$value,
        seed = function() private$..seed$value,
        permN = function() private$..permN$value,
        permRestriction = function() private$..permRestriction$value,
        permScheme = function() private$..permScheme$value,
        useParallel = function() private$..useParallel$value,
        dispType = function() private$..dispType$value,
        dispBias = function() private$..dispBias$value,
        dispPairwise = function() private$..dispPairwise$value,
        dispAdjust = function() private$..dispAdjust$value),
    private = list(
        ..vars = NA,
        ..factor = NA,
        ..transform = NA,
        ..distance = NA,
        ..distBinary = NA,
        ..distSqrt = NA,
        ..distAdd = NA,
        ..seed = NA,
        ..permN = NA,
        ..permRestriction = NA,
        ..permScheme = NA,
        ..useParallel = NA,
        ..dispType = NA,
        ..dispBias = NA,
        ..dispPairwise = NA,
        ..dispAdjust = NA)
)

permdispResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "permdispResults",
    inherit = jmvcore::Group,
    active = list(
        guidance = function() private$.items[["guidance"]],
        summary = function() private$.items[["summary"]],
        warnings = function() private$.items[["warnings"]],
        distances = function() private$.items[["distances"]],
        anova = function() private$.items[["anova"]],
        pairwise = function() private$.items[["pairwise"]],
        plot = function() private$.items[["plot"]],
        note = function() private$.items[["note"]],
        settings = function() private$.items[["settings"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="PERMDISP")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="guidance",
                title="Getting started",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Data Summary",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="item",
                        `title`="Item",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="warnings",
                title="Data handling warnings",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="distances",
                title="Distances to Group Centre",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="group",
                        `title`="Group",
                        `type`="text"),
                    list(
                        `name`="n",
                        `title`="n",
                        `type`="integer"),
                    list(
                        `name`="distance",
                        `title`="Mean distance",
                        `type`="number"),
                    list(
                        `name`="median",
                        `title`="Median distance",
                        `type`="number"),
                    list(
                        `name`="sd",
                        `title`="Standard deviation",
                        `type`="number"),
                    list(
                        `name`="min",
                        `title`="Minimum",
                        `type`="number"),
                    list(
                        `name`="max",
                        `title`="Maximum",
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="anova",
                title="Dispersion Test",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="source",
                        `title`="Source",
                        `type`="text"),
                    list(
                        `name`="df",
                        `title`="df",
                        `type`="integer"),
                    list(
                        `name`="sumsqs",
                        `title`="Sum Sq",
                        `type`="number"),
                    list(
                        `name`="meansq",
                        `title`="Mean Sq",
                        `type`="number"),
                    list(
                        `name`="f",
                        `title`="F",
                        `type`="number"),
                    list(
                        `name`="p",
                        `title`="Permutation p",
                        `type`="number",
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="pairwise",
                title="Pairwise Dispersion Comparisons",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="contrast",
                        `title`="Contrast",
                        `type`="text"),
                    list(
                        `name`="statistic",
                        `title`="t",
                        `type`="number"),
                    list(
                        `name`="p",
                        `title`="Permutation p",
                        `type`="number",
                        `format`="zto,pvalue"),
                    list(
                        `name`="padj",
                        `title`="Adjusted p",
                        `type`="number",
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Distance Distributions",
                visible=FALSE,
                width=600,
                height=450,
                renderFun=".plotDistances"))
            self$add(jmvcore::Html$new(
                options=options,
                name="note",
                title="Interpretation",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="settings",
                title="Analysis settings",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="setting",
                        `title`="Setting",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text"))))}))

permdispBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "permdispBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tofu",
                name = "permdisp",
                version = c(0,2,0),
                options = options,
                results = permdispResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' PERMDISP
#'
#'
#' @param data .
#' @param vars .
#' @param factor .
#' @param transform .
#' @param distance .
#' @param distBinary .
#' @param distSqrt .
#' @param distAdd .
#' @param seed .
#' @param permN .
#' @param permRestriction .
#' @param permScheme .
#' @param useParallel .
#' @param dispType .
#' @param dispBias .
#' @param dispPairwise .
#' @param dispAdjust .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$guidance} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$distances} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$anova} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pairwise} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$note} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$settings} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
permdisp <- function(
    data,
    vars,
    factor,
    transform = "none",
    distance = "bray",
    distBinary = FALSE,
    distSqrt = FALSE,
    distAdd = "none",
    seed = 0,
    permN = 999,
    permRestriction = "free",
    permScheme = "free",
    useParallel = FALSE,
    dispType = "median",
    dispBias = FALSE,
    dispPairwise = FALSE,
    dispAdjust = "holm") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("permdisp requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(factor)) factor <- jmvcore::resolveQuo(jmvcore::enquo(factor))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(factor), factor, NULL))

    for (v in factor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- permdispOptions$new(
        vars = vars,
        factor = factor,
        transform = transform,
        distance = distance,
        distBinary = distBinary,
        distSqrt = distSqrt,
        distAdd = distAdd,
        seed = seed,
        permN = permN,
        permRestriction = permRestriction,
        permScheme = permScheme,
        useParallel = useParallel,
        dispType = dispType,
        dispBias = dispBias,
        dispPairwise = dispPairwise,
        dispAdjust = dispAdjust)

    analysis <- permdispClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
