
# This file is automatically generated, you probably don't want to edit this

permanovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "permanovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            factor = NULL,
            permFactors = NULL,
            strata = NULL,
            covariates = NULL,
            transform = "none",
            distance = "bray",
            distBinary = FALSE,
            distSqrt = FALSE,
            distAdd = "none",
            seed = 0,
            permInteractions = FALSE,
            permN = 999,
            permScheme = "free",
            useParallel = FALSE,
            permBy = "terms",
            permPairwise = FALSE,
            permAdjust = "holm", ...) {

            super$initialize(
                package="tofu",
                name="permanova",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..factor <- jmvcore::OptionVariable$new(
                "factor",
                factor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..permFactors <- jmvcore::OptionVariables$new(
                "permFactors",
                permFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..strata <- jmvcore::OptionVariable$new(
                "strata",
                strata,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..transform <- jmvcore::OptionList$new(
                "transform",
                transform,
                options=list(
                    "none",
                    "sqrt",
                    "fourthroot",
                    "log",
                    "pa",
                    "wisconsin",
                    "hellinger",
                    "total",
                    "max",
                    "frequency",
                    "normalize",
                    "range",
                    "standardize",
                    "chi.square",
                    "rclr"),
                default="none")
            private$..distance <- jmvcore::OptionList$new(
                "distance",
                distance,
                options=list(
                    "bray",
                    "jaccard",
                    "euclidean",
                    "manhattan",
                    "canberra",
                    "kulczynski",
                    "gower",
                    "morisita",
                    "horn",
                    "mountford",
                    "raup",
                    "binomial",
                    "chao",
                    "cao",
                    "clark",
                    "altGower",
                    "mahalanobis"),
                default="bray")
            private$..distBinary <- jmvcore::OptionBool$new(
                "distBinary",
                distBinary,
                default=FALSE)
            private$..distSqrt <- jmvcore::OptionBool$new(
                "distSqrt",
                distSqrt,
                default=FALSE)
            private$..distAdd <- jmvcore::OptionList$new(
                "distAdd",
                distAdd,
                options=list(
                    "none",
                    "cailliez",
                    "lingoes"),
                default="none")
            private$..seed <- jmvcore::OptionNumber$new(
                "seed",
                seed,
                default=0,
                min=0)
            private$..permInteractions <- jmvcore::OptionBool$new(
                "permInteractions",
                permInteractions,
                default=FALSE)
            private$..permN <- jmvcore::OptionNumber$new(
                "permN",
                permN,
                default=999,
                min=1)
            private$..permScheme <- jmvcore::OptionList$new(
                "permScheme",
                permScheme,
                options=list(
                    "free",
                    "stratified",
                    "series"),
                default="free")
            private$..useParallel <- jmvcore::OptionBool$new(
                "useParallel",
                useParallel,
                default=FALSE)
            private$..permBy <- jmvcore::OptionList$new(
                "permBy",
                permBy,
                options=list(
                    "omnibus",
                    "terms",
                    "margin"),
                default="terms")
            private$..permPairwise <- jmvcore::OptionBool$new(
                "permPairwise",
                permPairwise,
                default=FALSE)
            private$..permAdjust <- jmvcore::OptionList$new(
                "permAdjust",
                permAdjust,
                options=list(
                    "holm",
                    "bonferroni",
                    "BH",
                    "BY",
                    "none"),
                default="holm")

            self$.addOption(private$..vars)
            self$.addOption(private$..factor)
            self$.addOption(private$..permFactors)
            self$.addOption(private$..strata)
            self$.addOption(private$..covariates)
            self$.addOption(private$..transform)
            self$.addOption(private$..distance)
            self$.addOption(private$..distBinary)
            self$.addOption(private$..distSqrt)
            self$.addOption(private$..distAdd)
            self$.addOption(private$..seed)
            self$.addOption(private$..permInteractions)
            self$.addOption(private$..permN)
            self$.addOption(private$..permScheme)
            self$.addOption(private$..useParallel)
            self$.addOption(private$..permBy)
            self$.addOption(private$..permPairwise)
            self$.addOption(private$..permAdjust)
        }),
    active = list(
        vars = function() private$..vars$value,
        factor = function() private$..factor$value,
        permFactors = function() private$..permFactors$value,
        strata = function() private$..strata$value,
        covariates = function() private$..covariates$value,
        transform = function() private$..transform$value,
        distance = function() private$..distance$value,
        distBinary = function() private$..distBinary$value,
        distSqrt = function() private$..distSqrt$value,
        distAdd = function() private$..distAdd$value,
        seed = function() private$..seed$value,
        permInteractions = function() private$..permInteractions$value,
        permN = function() private$..permN$value,
        permScheme = function() private$..permScheme$value,
        useParallel = function() private$..useParallel$value,
        permBy = function() private$..permBy$value,
        permPairwise = function() private$..permPairwise$value,
        permAdjust = function() private$..permAdjust$value),
    private = list(
        ..vars = NA,
        ..factor = NA,
        ..permFactors = NA,
        ..strata = NA,
        ..covariates = NA,
        ..transform = NA,
        ..distance = NA,
        ..distBinary = NA,
        ..distSqrt = NA,
        ..distAdd = NA,
        ..seed = NA,
        ..permInteractions = NA,
        ..permN = NA,
        ..permScheme = NA,
        ..useParallel = NA,
        ..permBy = NA,
        ..permPairwise = NA,
        ..permAdjust = NA)
)

permanovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "permanovaResults",
    inherit = jmvcore::Group,
    active = list(
        guidance = function() private$.items[["guidance"]],
        summary = function() private$.items[["summary"]],
        warnings = function() private$.items[["warnings"]],
        table = function() private$.items[["table"]],
        pairwise = function() private$.items[["pairwise"]],
        note = function() private$.items[["note"]],
        settings = function() private$.items[["settings"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="PERMANOVA")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="guidance",
                title="Getting started",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Data Summary",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="item",
                        `title`="Item",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="warnings",
                title="Data handling warnings",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="table",
                title="PERMANOVA Table",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="source",
                        `title`="Source",
                        `type`="text"),
                    list(
                        `name`="df",
                        `title`="df",
                        `type`="integer"),
                    list(
                        `name`="sumsqs",
                        `title`="Sum Sq",
                        `type`="number"),
                    list(
                        `name`="r2",
                        `title`="R\u00B2",
                        `type`="number"),
                    list(
                        `name`="f",
                        `title`="Pseudo-F",
                        `type`="number"),
                    list(
                        `name`="p",
                        `title`="Permutation p",
                        `type`="number",
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="pairwise",
                title="Pairwise PERMANOVA",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="contrast",
                        `title`="Contrast",
                        `type`="text"),
                    list(
                        `name`="f",
                        `title`="Pseudo-F",
                        `type`="number"),
                    list(
                        `name`="p",
                        `title`="Permutation p",
                        `type`="number",
                        `format`="zto,pvalue"),
                    list(
                        `name`="padj",
                        `title`="Adjusted p",
                        `type`="number",
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="note",
                title="Interpretation",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="settings",
                title="Analysis settings",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="setting",
                        `title`="Setting",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text"))))}))

permanovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "permanovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tofu",
                name = "permanova",
                version = c(0,2,0),
                options = options,
                results = permanovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' PERMANOVA
#'
#'
#' @param data .
#' @param vars .
#' @param factor .
#' @param permFactors .
#' @param strata .
#' @param covariates .
#' @param transform .
#' @param distance .
#' @param distBinary .
#' @param distSqrt .
#' @param distAdd .
#' @param seed .
#' @param permInteractions .
#' @param permN .
#' @param permScheme .
#' @param useParallel .
#' @param permBy .
#' @param permPairwise .
#' @param permAdjust .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$guidance} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pairwise} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$note} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$settings} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
permanova <- function(
    data,
    vars,
    factor,
    permFactors = NULL,
    strata = NULL,
    covariates = NULL,
    transform = "none",
    distance = "bray",
    distBinary = FALSE,
    distSqrt = FALSE,
    distAdd = "none",
    seed = 0,
    permInteractions = FALSE,
    permN = 999,
    permScheme = "free",
    useParallel = FALSE,
    permBy = "terms",
    permPairwise = FALSE,
    permAdjust = "holm") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("permanova requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(factor)) factor <- jmvcore::resolveQuo(jmvcore::enquo(factor))
    if ( ! missing(permFactors)) permFactors <- jmvcore::resolveQuo(jmvcore::enquo(permFactors))
    if ( ! missing(strata)) strata <- jmvcore::resolveQuo(jmvcore::enquo(strata))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(factor), factor, NULL),
            `if`( ! missing(permFactors), permFactors, NULL),
            `if`( ! missing(strata), strata, NULL),
            `if`( ! missing(covariates), covariates, NULL))

    for (v in factor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in permFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in strata) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- permanovaOptions$new(
        vars = vars,
        factor = factor,
        permFactors = permFactors,
        strata = strata,
        covariates = covariates,
        transform = transform,
        distance = distance,
        distBinary = distBinary,
        distSqrt = distSqrt,
        distAdd = distAdd,
        seed = seed,
        permInteractions = permInteractions,
        permN = permN,
        permScheme = permScheme,
        useParallel = useParallel,
        permBy = permBy,
        permPairwise = permPairwise,
        permAdjust = permAdjust)

    analysis <- permanovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
