
# This file is automatically generated, you probably don't want to edit this

permanovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "permanovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            factor = NULL,
            permFactors = NULL,
            strata = NULL,
            covariates = NULL,
            transform = "none",
            distance = "bray",
            distBinary = FALSE,
            distSqrt = FALSE,
            distAdd = "none",
            seed = 0,
            permInteractions = FALSE,
            permN = 999,
            permScheme = "free",
            useParallel = FALSE,
            permBy = "terms",
            permPairwise = FALSE,
            permAdjust = "holm",
            showCompanionPcoa = FALSE,
            pcoaDisplayFactor = NULL,
            pcoaCentroids = FALSE,
            pcoaSpiders = FALSE, ...) {

            super$initialize(
                package="miso",
                name="permanova",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..factor <- jmvcore::OptionVariable$new(
                "factor",
                factor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..permFactors <- jmvcore::OptionVariables$new(
                "permFactors",
                permFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..strata <- jmvcore::OptionVariable$new(
                "strata",
                strata,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..transform <- jmvcore::OptionList$new(
                "transform",
                transform,
                options=list(
                    "none",
                    "sqrt",
                    "fourthroot",
                    "log",
                    "pa",
                    "wisconsin",
                    "hellinger",
                    "total",
                    "max",
                    "frequency",
                    "normalize",
                    "range",
                    "standardize",
                    "chi.square",
                    "rclr"),
                default="none")
            private$..distance <- jmvcore::OptionList$new(
                "distance",
                distance,
                options=list(
                    "bray",
                    "jaccard",
                    "euclidean",
                    "manhattan",
                    "canberra",
                    "kulczynski",
                    "gower",
                    "morisita",
                    "horn",
                    "mountford",
                    "raup",
                    "binomial",
                    "chao",
                    "cao",
                    "clark",
                    "altGower",
                    "mahalanobis"),
                default="bray")
            private$..distBinary <- jmvcore::OptionBool$new(
                "distBinary",
                distBinary,
                default=FALSE)
            private$..distSqrt <- jmvcore::OptionBool$new(
                "distSqrt",
                distSqrt,
                default=FALSE)
            private$..distAdd <- jmvcore::OptionList$new(
                "distAdd",
                distAdd,
                options=list(
                    "none",
                    "cailliez",
                    "lingoes"),
                default="none")
            private$..seed <- jmvcore::OptionNumber$new(
                "seed",
                seed,
                default=0,
                min=0)
            private$..permInteractions <- jmvcore::OptionBool$new(
                "permInteractions",
                permInteractions,
                default=FALSE)
            private$..permN <- jmvcore::OptionNumber$new(
                "permN",
                permN,
                default=999,
                min=1)
            private$..permScheme <- jmvcore::OptionList$new(
                "permScheme",
                permScheme,
                options=list(
                    "free",
                    "stratified",
                    "series"),
                default="free")
            private$..useParallel <- jmvcore::OptionBool$new(
                "useParallel",
                useParallel,
                default=FALSE)
            private$..permBy <- jmvcore::OptionList$new(
                "permBy",
                permBy,
                options=list(
                    "omnibus",
                    "terms",
                    "margin"),
                default="terms")
            private$..permPairwise <- jmvcore::OptionBool$new(
                "permPairwise",
                permPairwise,
                default=FALSE)
            private$..permAdjust <- jmvcore::OptionList$new(
                "permAdjust",
                permAdjust,
                options=list(
                    "holm",
                    "bonferroni",
                    "BH",
                    "BY",
                    "none"),
                default="holm")
            private$..showCompanionPcoa <- jmvcore::OptionBool$new(
                "showCompanionPcoa",
                showCompanionPcoa,
                default=FALSE)
            private$..pcoaDisplayFactor <- jmvcore::OptionVariable$new(
                "pcoaDisplayFactor",
                pcoaDisplayFactor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric"),
                default=NULL)
            private$..pcoaCentroids <- jmvcore::OptionBool$new(
                "pcoaCentroids",
                pcoaCentroids,
                default=FALSE)
            private$..pcoaSpiders <- jmvcore::OptionBool$new(
                "pcoaSpiders",
                pcoaSpiders,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..factor)
            self$.addOption(private$..permFactors)
            self$.addOption(private$..strata)
            self$.addOption(private$..covariates)
            self$.addOption(private$..transform)
            self$.addOption(private$..distance)
            self$.addOption(private$..distBinary)
            self$.addOption(private$..distSqrt)
            self$.addOption(private$..distAdd)
            self$.addOption(private$..seed)
            self$.addOption(private$..permInteractions)
            self$.addOption(private$..permN)
            self$.addOption(private$..permScheme)
            self$.addOption(private$..useParallel)
            self$.addOption(private$..permBy)
            self$.addOption(private$..permPairwise)
            self$.addOption(private$..permAdjust)
            self$.addOption(private$..showCompanionPcoa)
            self$.addOption(private$..pcoaDisplayFactor)
            self$.addOption(private$..pcoaCentroids)
            self$.addOption(private$..pcoaSpiders)
        }),
    active = list(
        vars = function() private$..vars$value,
        factor = function() private$..factor$value,
        permFactors = function() private$..permFactors$value,
        strata = function() private$..strata$value,
        covariates = function() private$..covariates$value,
        transform = function() private$..transform$value,
        distance = function() private$..distance$value,
        distBinary = function() private$..distBinary$value,
        distSqrt = function() private$..distSqrt$value,
        distAdd = function() private$..distAdd$value,
        seed = function() private$..seed$value,
        permInteractions = function() private$..permInteractions$value,
        permN = function() private$..permN$value,
        permScheme = function() private$..permScheme$value,
        useParallel = function() private$..useParallel$value,
        permBy = function() private$..permBy$value,
        permPairwise = function() private$..permPairwise$value,
        permAdjust = function() private$..permAdjust$value,
        showCompanionPcoa = function() private$..showCompanionPcoa$value,
        pcoaDisplayFactor = function() private$..pcoaDisplayFactor$value,
        pcoaCentroids = function() private$..pcoaCentroids$value,
        pcoaSpiders = function() private$..pcoaSpiders$value),
    private = list(
        ..vars = NA,
        ..factor = NA,
        ..permFactors = NA,
        ..strata = NA,
        ..covariates = NA,
        ..transform = NA,
        ..distance = NA,
        ..distBinary = NA,
        ..distSqrt = NA,
        ..distAdd = NA,
        ..seed = NA,
        ..permInteractions = NA,
        ..permN = NA,
        ..permScheme = NA,
        ..useParallel = NA,
        ..permBy = NA,
        ..permPairwise = NA,
        ..permAdjust = NA,
        ..showCompanionPcoa = NA,
        ..pcoaDisplayFactor = NA,
        ..pcoaCentroids = NA,
        ..pcoaSpiders = NA)
)

permanovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "permanovaResults",
    inherit = jmvcore::Group,
    active = list(
        guidance = function() private$.items[["guidance"]],
        warnings = function() private$.items[["warnings"]],
        table = function() private$.items[["table"]],
        companionPcoaDescription = function() private$.items[["companionPcoaDescription"]],
        companionPcoa = function() private$.items[["companionPcoa"]],
        companionPcoaSites = function() private$.items[["companionPcoaSites"]],
        companionPcoaCentroids = function() private$.items[["companionPcoaCentroids"]],
        pairwise = function() private$.items[["pairwise"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="PERMANOVA",
                refs=list(
                    "vegan",
                    "anderson2001"))
            self$add(jmvcore::Html$new(
                options=options,
                name="guidance",
                title="Getting Started",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="warnings",
                title="",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="table",
                title="PERMANOVA Results",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="source",
                        `title`="Source",
                        `type`="text"),
                    list(
                        `name`="df",
                        `title`="df",
                        `type`="integer"),
                    list(
                        `name`="sumsqs",
                        `title`="Sum Sq",
                        `type`="number"),
                    list(
                        `name`="r2",
                        `title`="R\u00B2",
                        `type`="number"),
                    list(
                        `name`="f",
                        `title`="Pseudo-F",
                        `type`="number"),
                    list(
                        `name`="p",
                        `title`="Permutation p",
                        `type`="number",
                        `format`="zto,pvalue")),
                clearWith=list(
                    "vars",
                    "factor",
                    "permFactors",
                    "covariates",
                    "strata",
                    "permInteractions",
                    "permBy",
                    "transform",
                    "distance",
                    "distBinary",
                    "distSqrt",
                    "distAdd",
                    "permN",
                    "seed",
                    "useParallel")))
            self$add(jmvcore::Html$new(
                options=options,
                name="companionPcoaDescription",
                title="PERMANOVA Companion PCoA",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "factor",
                    "permFactors",
                    "covariates",
                    "strata",
                    "permInteractions",
                    "permBy",
                    "transform",
                    "distance",
                    "distBinary",
                    "distSqrt",
                    "distAdd")))
            self$add(jmvcore::Image$new(
                options=options,
                name="companionPcoa",
                title="Companion PCoA",
                width=600,
                height=500,
                renderFun=".plotCompanionPcoa",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "factor",
                    "permFactors",
                    "covariates",
                    "strata",
                    "permInteractions",
                    "permBy",
                    "transform",
                    "distance",
                    "distBinary",
                    "distSqrt",
                    "distAdd")))
            self$add(jmvcore::Table$new(
                options=options,
                name="companionPcoaSites",
                title="Companion PCoA Site Coordinates",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="site",
                        `title`="Site",
                        `type`="text"),
                    list(
                        `name`="sourceRow",
                        `title`="Source row",
                        `type`="integer"),
                    list(
                        `name`="group",
                        `title`="Group",
                        `type`="text"),
                    list(
                        `name`="PCoA1",
                        `title`="PCoA1",
                        `type`="number",
                        `format`="zto"),
                    list(
                        `name`="PCoA2",
                        `title`="PCoA2",
                        `type`="number",
                        `format`="zto")),
                clearWith=list(
                    "vars",
                    "factor",
                    "permFactors",
                    "covariates",
                    "strata",
                    "permInteractions",
                    "permBy",
                    "transform",
                    "distance",
                    "distBinary",
                    "distSqrt",
                    "distAdd")))
            self$add(jmvcore::Table$new(
                options=options,
                name="companionPcoaCentroids",
                title="Companion PCoA Group Centroids",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="group",
                        `title`="Group",
                        `type`="text"),
                    list(
                        `name`="n",
                        `title`="n",
                        `type`="integer"),
                    list(
                        `name`="PCoA1",
                        `title`="PCoA1",
                        `type`="number",
                        `format`="zto"),
                    list(
                        `name`="PCoA2",
                        `title`="PCoA2",
                        `type`="number",
                        `format`="zto")),
                clearWith=list(
                    "vars",
                    "factor",
                    "permFactors",
                    "covariates",
                    "strata",
                    "permInteractions",
                    "permBy",
                    "transform",
                    "distance",
                    "distBinary",
                    "distSqrt",
                    "distAdd")))
            self$add(jmvcore::Table$new(
                options=options,
                name="pairwise",
                title="Pairwise PERMANOVA",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="contrast",
                        `title`="Contrast",
                        `type`="text"),
                    list(
                        `name`="f",
                        `title`="Pseudo-F",
                        `type`="number"),
                    list(
                        `name`="p",
                        `title`="Permutation p",
                        `type`="number",
                        `format`="zto,pvalue"),
                    list(
                        `name`="padj",
                        `title`="Adjusted p",
                        `type`="number",
                        `format`="zto,pvalue"))))}))

permanovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "permanovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "miso",
                name = "permanova",
                version = c(1,0,0),
                options = options,
                results = permanovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' PERMANOVA
#'
#' Tests whether multivariate composition is associated with one or more
#' predictors using PERMANOVA through vegan::adonis2. Supports restricted
#' permutations, pairwise comparisons, and a descriptive companion PCoA.
#' @section References:
#' Oksanen et al. (2026). vegan: Community Ecology Package (R package version 2.7-5). https://vegandevs.github.io/vegan/
#'
#' Anderson, M. J. (2001). A new method for non-parametric multivariate analysis of variance. Austral Ecology, 26(1), 32-46. https://doi.org/10.1111/j.1442-9993.2001.01070.pp.x
#'
#' @param data .
#' @param vars .
#' @param factor .
#' @param permFactors .
#' @param strata .
#' @param covariates .
#' @param transform .
#' @param distance .
#' @param distBinary .
#' @param distSqrt .
#' @param distAdd .
#' @param seed .
#' @param permInteractions .
#' @param permN .
#' @param permScheme .
#' @param useParallel .
#' @param permBy .
#' @param permPairwise .
#' @param permAdjust .
#' @param showCompanionPcoa Whether to show a descriptive PCoA based on the
#'   exact distance settings used by PERMANOVA.
#' @param pcoaDisplayFactor For multifactor models, choose the same primary or
#'   additional factor already included and retained in the fitted PERMANOVA
#'   model; other variables are rejected.
#' @param pcoaCentroids Whether to draw and tabulate group centroids in the
#'   companion PCoA.
#' @param pcoaSpiders Whether to connect displayed sites to their group
#'   centroid; spiders also show centroids.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$guidance} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$companionPcoaDescription} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$companionPcoa} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$companionPcoaSites} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$companionPcoaCentroids} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pairwise} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$table$asDF}
#'
#' \code{as.data.frame(results$table)}
#'
#' @export
permanova <- function(
    data,
    vars,
    factor,
    permFactors = NULL,
    strata = NULL,
    covariates = NULL,
    transform = "none",
    distance = "bray",
    distBinary = FALSE,
    distSqrt = FALSE,
    distAdd = "none",
    seed = 0,
    permInteractions = FALSE,
    permN = 999,
    permScheme = "free",
    useParallel = FALSE,
    permBy = "terms",
    permPairwise = FALSE,
    permAdjust = "holm",
    showCompanionPcoa = FALSE,
    pcoaDisplayFactor = NULL,
    pcoaCentroids = FALSE,
    pcoaSpiders = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("permanova requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(factor)) factor <- jmvcore::resolveQuo(jmvcore::enquo(factor))
    if ( ! missing(permFactors)) permFactors <- jmvcore::resolveQuo(jmvcore::enquo(permFactors))
    if ( ! missing(strata)) strata <- jmvcore::resolveQuo(jmvcore::enquo(strata))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if ( ! missing(pcoaDisplayFactor)) pcoaDisplayFactor <- jmvcore::resolveQuo(jmvcore::enquo(pcoaDisplayFactor))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(factor), factor, NULL),
            `if`( ! missing(permFactors), permFactors, NULL),
            `if`( ! missing(strata), strata, NULL),
            `if`( ! missing(covariates), covariates, NULL),
            `if`( ! missing(pcoaDisplayFactor), pcoaDisplayFactor, NULL))

    for (v in factor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in permFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in strata) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- permanovaOptions$new(
        vars = vars,
        factor = factor,
        permFactors = permFactors,
        strata = strata,
        covariates = covariates,
        transform = transform,
        distance = distance,
        distBinary = distBinary,
        distSqrt = distSqrt,
        distAdd = distAdd,
        seed = seed,
        permInteractions = permInteractions,
        permN = permN,
        permScheme = permScheme,
        useParallel = useParallel,
        permBy = permBy,
        permPairwise = permPairwise,
        permAdjust = permAdjust,
        showCompanionPcoa = showCompanionPcoa,
        pcoaDisplayFactor = pcoaDisplayFactor,
        pcoaCentroids = pcoaCentroids,
        pcoaSpiders = pcoaSpiders)

    analysis <- permanovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
