
# This file is automatically generated, you probably don't want to edit this

simperOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simperOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            factor = NULL,
            transform = "none",
            distance = "bray",
            distBinary = FALSE,
            seed = 0,
            simperN = 999,
            simperTop = 10,
            simperCum = 70, ...) {

            super$initialize(
                package="tofu",
                name="simper",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..factor <- jmvcore::OptionVariable$new(
                "factor",
                factor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..transform <- jmvcore::OptionList$new(
                "transform",
                transform,
                options=list(
                    "none",
                    "sqrt",
                    "fourthroot",
                    "log",
                    "pa",
                    "wisconsin",
                    "hellinger",
                    "total",
                    "max",
                    "frequency",
                    "normalize",
                    "range",
                    "standardize",
                    "chi.square",
                    "rclr"),
                default="none")
            private$..distance <- jmvcore::OptionList$new(
                "distance",
                distance,
                options=list(
                    "bray",
                    "jaccard",
                    "euclidean",
                    "manhattan",
                    "canberra",
                    "kulczynski",
                    "gower",
                    "morisita",
                    "horn",
                    "mountford",
                    "raup",
                    "binomial",
                    "chao",
                    "cao",
                    "clark",
                    "altGower",
                    "mahalanobis"),
                default="bray")
            private$..distBinary <- jmvcore::OptionBool$new(
                "distBinary",
                distBinary,
                default=FALSE)
            private$..seed <- jmvcore::OptionNumber$new(
                "seed",
                seed,
                default=0,
                min=0)
            private$..simperN <- jmvcore::OptionNumber$new(
                "simperN",
                simperN,
                default=999,
                min=1)
            private$..simperTop <- jmvcore::OptionNumber$new(
                "simperTop",
                simperTop,
                default=10,
                min=1)
            private$..simperCum <- jmvcore::OptionNumber$new(
                "simperCum",
                simperCum,
                default=70,
                min=1,
                max=100)

            self$.addOption(private$..vars)
            self$.addOption(private$..factor)
            self$.addOption(private$..transform)
            self$.addOption(private$..distance)
            self$.addOption(private$..distBinary)
            self$.addOption(private$..seed)
            self$.addOption(private$..simperN)
            self$.addOption(private$..simperTop)
            self$.addOption(private$..simperCum)
        }),
    active = list(
        vars = function() private$..vars$value,
        factor = function() private$..factor$value,
        transform = function() private$..transform$value,
        distance = function() private$..distance$value,
        distBinary = function() private$..distBinary$value,
        seed = function() private$..seed$value,
        simperN = function() private$..simperN$value,
        simperTop = function() private$..simperTop$value,
        simperCum = function() private$..simperCum$value),
    private = list(
        ..vars = NA,
        ..factor = NA,
        ..transform = NA,
        ..distance = NA,
        ..distBinary = NA,
        ..seed = NA,
        ..simperN = NA,
        ..simperTop = NA,
        ..simperCum = NA)
)

simperResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simperResults",
    inherit = jmvcore::Group,
    active = list(
        warnings = function() private$.items[["warnings"]],
        summary = function() private$.items[["summary"]],
        table = function() private$.items[["table"]],
        plot = function() private$.items[["plot"]],
        note = function() private$.items[["note"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="SIMPER")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="warnings",
                title="Notes and Warnings"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Data Summary",
                rows=0,
                columns=list(
                    list(
                        `name`="item",
                        `title`="Item",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="table",
                title="Feature Contributions",
                rows=0,
                columns=list(
                    list(
                        `name`="contrast",
                        `title`="Contrast",
                        `type`="text"),
                    list(
                        `name`="feature",
                        `title`="Feature",
                        `type`="text"),
                    list(
                        `name`="average",
                        `title`="Average",
                        `type`="number"),
                    list(
                        `name`="sd",
                        `title`="SD",
                        `type`="number"),
                    list(
                        `name`="ratio",
                        `title`="Ratio",
                        `type`="number"),
                    list(
                        `name`="contribution",
                        `title`="Contribution %",
                        `type`="number"),
                    list(
                        `name`="cumulative",
                        `title`="Cumulative %",
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Contribution Plot",
                width=650,
                height=450,
                renderFun=".plotContributions"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="note",
                title="Notes"))}))

simperBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simperBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tofu",
                name = "simper",
                version = c(0,2,0),
                options = options,
                results = simperResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' SIMPER
#'
#'
#' @param data .
#' @param vars .
#' @param factor .
#' @param transform .
#' @param distance .
#' @param distBinary .
#' @param seed .
#' @param simperN .
#' @param simperTop .
#' @param simperCum .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$warnings} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$note} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
simper <- function(
    data,
    vars,
    factor,
    transform = "none",
    distance = "bray",
    distBinary = FALSE,
    seed = 0,
    simperN = 999,
    simperTop = 10,
    simperCum = 70) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("simper requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(factor)) factor <- jmvcore::resolveQuo(jmvcore::enquo(factor))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(factor), factor, NULL))

    for (v in factor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- simperOptions$new(
        vars = vars,
        factor = factor,
        transform = transform,
        distance = distance,
        distBinary = distBinary,
        seed = seed,
        simperN = simperN,
        simperTop = simperTop,
        simperCum = simperCum)

    analysis <- simperClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
